name: Hello GitHub Actions

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions! "
      
      - name: Show current time
        run: date
      
      - name: List files
        run: ls -la
      - name: read a file
        run: cat README.md
